"""empty message

Revision ID: 4a9043408f83
Revises: ca726193cf6e
Create Date: 2024-03-11 02:20:10.946513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a9043408f83'
down_revision = 'ca726193cf6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isbn', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('section_name', sa.String(length=255), nullable=True))
        batch_op.create_unique_constraint(None, ['isbn'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('section_name')
        batch_op.drop_column('isbn')

    # ### end Alembic commands ###
