"""book class changed

Revision ID: a6e0b6c35e12
Revises: bf3ffbdd4909
Create Date: 2024-03-11 09:35:49.209807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6e0b6c35e12'
down_revision = 'bf3ffbdd4909'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isbn', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('section_name', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_column('section_name')
        batch_op.drop_column('isbn')

    # ### end Alembic commands ###
